/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JogadoresRouteImport } from './routes/jogadores'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartidasRouteImport } from './routes/partidas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadoresRoute = JogadoresRouteImport.update({
  id: '/jogadores',
  path: '/jogadores',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidasRoute = PartidasRouteImport.update({
  id: '/partidas',
  path: '/partidas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jogadores': typeof JogadoresRoute
  '/login': typeof LoginRoute
  '/partidas': typeof PartidasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jogadores': typeof JogadoresRoute
  '/login': typeof LoginRoute
  '/partidas': typeof PartidasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jogadores': typeof JogadoresRoute
  '/login': typeof LoginRoute
  '/partidas': typeof PartidasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jogadores' | '/login' | '/partidas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jogadores' | '/login' | '/partidas'
  id: '__root__' | '/' | '/jogadores' | '/login' | '/partidas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JogadoresRoute: typeof JogadoresRoute
  LoginRoute: typeof LoginRoute
  PartidasRoute: typeof PartidasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogadores': {
      id: '/jogadores'
      path: '/jogadores'
      fullPath: '/jogadores'
      preLoaderRoute: typeof JogadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidas': {
      id: '/partidas'
      path: '/partidas'
      fullPath: '/partidas'
      preLoaderRoute: typeof PartidasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JogadoresRoute: JogadoresRoute,
  LoginRoute: LoginRoute,
  PartidasRoute: PartidasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
